import { Team, Stat } from './types';

export const stats: Stat[] = [
  {
    id: "offensiveEfficiency",
    name: "Offensive Efficiency",
    description: "Points scored per 100 possessions",
    min: 90,
    max: 130,
    defaultWeight: 1,
    format: (value) => value.toFixed(1),
  },
  {
    id: "defensiveEfficiency",
    name: "Defensive Efficiency",
    description: "Points allowed per 100 possessions",
    min: 85,
    max: 110,
    defaultWeight: 1,
    format: (value) => value.toFixed(1),
  },
  {
    id: "pace",
    name: "Pace",
    description: "Possessions per 40 minutes",
    min: 60,
    max: 85,
    defaultWeight: 0.5,
    format: (value) => value.toFixed(1),
  },
  {
    id: "threePointPercentage",
    name: "3PT%",
    description: "Three-point shooting percentage",
    min: 30,
    max: 45,
    defaultWeight: 0.8,
    format: (value) => `${value.toFixed(1)}%`,
  },
  {
    id: "freeThrowPercentage",
    name: "FT%",
    description: "Free throw percentage",
    min: 65,
    max: 85,
    defaultWeight: 0.6,
    format: (value) => `${value.toFixed(1)}%`,
  },
  {
    id: "reboundRate",
    name: "Rebound Rate",
    description: "Percentage of rebounds secured",
    min: 45,
    max: 60,
    defaultWeight: 0.7,
    format: (value) => `${value.toFixed(1)}%`,
  },
  {
    id: "turnoverRate",
    name: "Turnover Rate",
    description: "Turnovers per 100 possessions",
    min: 12,
    max: 22,
    defaultWeight: 0.7,
    format: (value) => value.toFixed(1),
  },
  {
    id: "experienceRating",
    name: "Experience",
    description: "Team experience rating",
    min: 1,
    max: 5,
    defaultWeight: 0.6,
    format: (value) => value.toFixed(1),
  },
];

// 2025 March Madness teams
export const teams: Team[] = [
  // South Region
  {
    id: "auburn",
    name: "Auburn",
    seed: 1,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Auburn_Tigers_logo.svg/1200px-Auburn_Tigers_logo.svg.png",
    colors: {
      primary: "#0C2340",
      secondary: "#E87722",
    },
    stats: {
      offensiveEfficiency: 120.5,
      defensiveEfficiency: 90.2,
      pace: 72.1,
      threePointPercentage: 38.2,
      freeThrowPercentage: 75.5,
      reboundRate: 55.8,
      turnoverRate: 15.2,
      experienceRating: 4.1,
    },
  },
  {
    id: "alabama_st",
    name: "Alabama St.",
    seed: 16,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Alabama_State_Hornets_logo.svg/1200px-Alabama_State_Hornets_logo.svg.png",
    colors: {
      primary: "#000000",
      secondary: "#CFB53B",
    },
    stats: {
      offensiveEfficiency: 98.5,
      defensiveEfficiency: 102.8,
      pace: 68.4,
      threePointPercentage: 32.1,
      freeThrowPercentage: 68.9,
      reboundRate: 48.2,
      turnoverRate: 19.5,
      experienceRating: 2.8,
    },
  },
  {
    id: "louisville",
    name: "Louisville",
    seed: 8,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Louisville_Cardinals_logo.svg/1200px-Louisville_Cardinals_logo.svg.png",
    colors: {
      primary: "#AD0000",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 112.3,
      defensiveEfficiency: 95.7,
      pace: 69.8,
      threePointPercentage: 35.6,
      freeThrowPercentage: 73.2,
      reboundRate: 52.1,
      turnoverRate: 16.8,
      experienceRating: 3.5,
    },
  },
  {
    id: "creighton",
    name: "Creighton",
    seed: 9,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Creighton_Bluejays_logo.svg/1200px-Creighton_Bluejays_logo.svg.png",
    colors: {
      primary: "#003087",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 114.8,
      defensiveEfficiency: 94.3,
      pace: 68.2,
      threePointPercentage: 37.8,
      freeThrowPercentage: 74.5,
      reboundRate: 51.9,
      turnoverRate: 15.9,
      experienceRating: 3.8,
    },
  },
  {
    id: "michigan",
    name: "Michigan",
    seed: 5,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Michigan_Wolverines_logo.svg/1200px-Michigan_Wolverines_logo.svg.png",
    colors: {
      primary: "#00274C",
      secondary: "#FFCB05",
    },
    stats: {
      offensiveEfficiency: 115.2,
      defensiveEfficiency: 96.8,
      pace: 70.1,
      threePointPercentage: 36.4,
      freeThrowPercentage: 74.8,
      reboundRate: 53.2,
      turnoverRate: 16.5,
      experienceRating: 3.7,
    },
  },
  {
    id: "uc_san_diego",
    name: "UC San Diego",
    seed: 12,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/UC_San_Diego_Tritons_logo.svg/1200px-UC_San_Diego_Tritons_logo.svg.png",
    colors: {
      primary: "#00629B",
      secondary: "#FFCD00",
    },
    stats: {
      offensiveEfficiency: 108.9,
      defensiveEfficiency: 98.5,
      pace: 67.8,
      threePointPercentage: 35.2,
      freeThrowPercentage: 71.5,
      reboundRate: 50.8,
      turnoverRate: 17.2,
      experienceRating: 3.1,
    },
  },
  {
    id: "texas_am",
    name: "Texas A&M",
    seed: 4,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Texas_A%26M_Athletics_logo.svg/1200px-Texas_A%26M_Athletics_logo.svg.png",
    colors: {
      primary: "#500000",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 116.8,
      defensiveEfficiency: 93.4,
      pace: 69.5,
      threePointPercentage: 36.8,
      freeThrowPercentage: 75.2,
      reboundRate: 54.1,
      turnoverRate: 15.8,
      experienceRating: 3.9,
    },
  },
  {
    id: "yale",
    name: "Yale",
    seed: 13,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Yale_Bulldogs_logo.svg/1200px-Yale_Bulldogs_logo.svg.png",
    colors: {
      primary: "#00356B",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 107.2,
      defensiveEfficiency: 99.1,
      pace: 66.5,
      threePointPercentage: 34.8,
      freeThrowPercentage: 72.8,
      reboundRate: 51.2,
      turnoverRate: 17.5,
      experienceRating: 3.2,
    },
  },
  {
    id: "ole_miss",
    name: "Ole Miss",
    seed: 6,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Ole_Miss_Rebels_logo.svg/1200px-Ole_Miss_Rebels_logo.svg.png",
    colors: {
      primary: "#CE1126",
      secondary: "#006BA6",
    },
    stats: {
      offensiveEfficiency: 113.5,
      defensiveEfficiency: 95.2,
      pace: 70.8,
      threePointPercentage: 35.9,
      freeThrowPercentage: 73.8,
      reboundRate: 52.5,
      turnoverRate: 16.2,
      experienceRating: 3.6,
    },
  },
  {
    id: "north_carolina",
    name: "North Carolina",
    seed: 11,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/North_Carolina_Tar_Heels_logo.svg/1200px-North_Carolina_Tar_Heels_logo.svg.png",
    colors: {
      primary: "#7BAFD4",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 111.8,
      defensiveEfficiency: 96.5,
      pace: 69.2,
      threePointPercentage: 35.5,
      freeThrowPercentage: 73.5,
      reboundRate: 52.8,
      turnoverRate: 16.9,
      experienceRating: 3.4,
    },
  },
  {
    id: "iowa_st",
    name: "Iowa St.",
    seed: 3,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Iowa_State_Cyclones_logo.svg/1200px-Iowa_State_Cyclones_logo.svg.png",
    colors: {
      primary: "#C8102E",
      secondary: "#F1BE48",
    },
    stats: {
      offensiveEfficiency: 117.2,
      defensiveEfficiency: 92.8,
      pace: 68.5,
      threePointPercentage: 36.5,
      freeThrowPercentage: 74.2,
      reboundRate: 53.5,
      turnoverRate: 15.5,
      experienceRating: 3.8,
    },
  },
  {
    id: "lipscomb",
    name: "Lipscomb",
    seed: 14,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Lipscomb_Bisons_logo.svg/1200px-Lipscomb_Bisons_logo.svg.png",
    colors: {
      primary: "#331E54",
      secondary: "#F4AA00",
    },
    stats: {
      offensiveEfficiency: 106.5,
      defensiveEfficiency: 99.8,
      pace: 67.2,
      threePointPercentage: 34.2,
      freeThrowPercentage: 71.8,
      reboundRate: 50.5,
      turnoverRate: 17.8,
      experienceRating: 3.0,
    },
  },
  {
    id: "marquette",
    name: "Marquette",
    seed: 7,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Marquette_Golden_Eagles_logo.svg/1200px-Marquette_Golden_Eagles_logo.svg.png",
    colors: {
      primary: "#003366",
      secondary: "#FFCC00",
    },
    stats: {
      offensiveEfficiency: 115.8,
      defensiveEfficiency: 94.5,
      pace: 69.8,
      threePointPercentage: 37.2,
      freeThrowPercentage: 74.5,
      reboundRate: 52.2,
      turnoverRate: 16.1,
      experienceRating: 3.7,
    },
  },
  {
    id: "new_mexico",
    name: "New Mexico",
    seed: 10,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/New_Mexico_Lobos_logo.svg/1200px-New_Mexico_Lobos_logo.svg.png",
    colors: {
      primary: "#BA0C2F",
      secondary: "#63666A",
    },
    stats: {
      offensiveEfficiency: 110.5,
      defensiveEfficiency: 97.2,
      pace: 70.5,
      threePointPercentage: 35.1,
      freeThrowPercentage: 72.8,
      reboundRate: 51.5,
      turnoverRate: 17.2,
      experienceRating: 3.3,
    },
  },
  {
    id: "michigan_st",
    name: "Michigan St.",
    seed: 2,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Michigan_State_Athletics_logo.svg/1200px-Michigan_State_Athletics_logo.svg.png",
    colors: {
      primary: "#18453B",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 118.5,
      defensiveEfficiency: 91.8,
      pace: 68.8,
      threePointPercentage: 37.5,
      freeThrowPercentage: 75.8,
      reboundRate: 54.5,
      turnoverRate: 15.2,
      experienceRating: 4.0,
    },
  },
  {
    id: "bryant",
    name: "Bryant",
    seed: 15,
    region: "South",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Bryant_Bulldogs_logo.svg/1200px-Bryant_Bulldogs_logo.svg.png",
    colors: {
      primary: "#000000",
      secondary: "#A60000",
    },
    stats: {
      offensiveEfficiency: 105.2,
      defensiveEfficiency: 100.5,
      pace: 67.5,
      threePointPercentage: 33.8,
      freeThrowPercentage: 71.2,
      reboundRate: 49.8,
      turnoverRate: 18.2,
      experienceRating: 2.9,
    },
  },
  // East Region
  {
    id: "duke",
    name: "Duke",
    seed: 1,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Duke_Athletics_logo.svg/1200px-Duke_Athletics_logo.svg.png",
    colors: {
      primary: "#003087",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 119.8,
      defensiveEfficiency: 91.2,
      pace: 69.5,
      threePointPercentage: 37.8,
      freeThrowPercentage: 75.2,
      reboundRate: 54.8,
      turnoverRate: 15.1,
      experienceRating: 4.0,
    },
  },
  {
    id: "mount_st_marys",
    name: "Mount St. Mary's",
    seed: 16,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Mount_St._Mary%27s_Mountaineers_logo.svg/1200px-Mount_St._Mary%27s_Mountaineers_logo.svg.png",
    colors: {
      primary: "#002D72",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 99.5,
      defensiveEfficiency: 101.8,
      pace: 67.2,
      threePointPercentage: 32.8,
      freeThrowPercentage: 69.5,
      reboundRate: 48.5,
      turnoverRate: 18.8,
      experienceRating: 2.9,
    },
  },
  {
    id: "mississippi_st",
    name: "Mississippi St.",
    seed: 8,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Mississippi_State_Bulldogs_logo.svg/1200px-Mississippi_State_Bulldogs_logo.svg.png",
    colors: {
      primary: "#660000",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 112.8,
      defensiveEfficiency: 95.5,
      pace: 69.2,
      threePointPercentage: 35.8,
      freeThrowPercentage: 73.5,
      reboundRate: 52.2,
      turnoverRate: 16.5,
      experienceRating: 3.6,
    },
  },
  {
    id: "baylor",
    name: "Baylor",
    seed: 9,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Baylor_Athletics_logo.svg/1200px-Baylor_Athletics_logo.svg.png",
    colors: {
      primary: "#003015",
      secondary: "#FFB81C",
    },
    stats: {
      offensiveEfficiency: 113.5,
      defensiveEfficiency: 94.8,
      pace: 68.8,
      threePointPercentage: 36.2,
      freeThrowPercentage: 74.1,
      reboundRate: 52.5,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "oregon",
    name: "Oregon",
    seed: 5,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Oregon_Ducks_logo.svg/1200px-Oregon_Ducks_logo.svg.png",
    colors: {
      primary: "#154733",
      secondary: "#FEE123",
    },
    stats: {
      offensiveEfficiency: 115.5,
      defensiveEfficiency: 95.2,
      pace: 70.5,
      threePointPercentage: 36.5,
      freeThrowPercentage: 74.2,
      reboundRate: 53.1,
      turnoverRate: 16.1,
      experienceRating: 3.8,
    },
  },
  {
    id: "liberty",
    name: "Liberty",
    seed: 12,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Liberty_Flames_logo.svg/1200px-Liberty_Flames_logo.svg.png",
    colors: {
      primary: "#002D62",
      secondary: "#C41230",
    },
    stats: {
      offensiveEfficiency: 108.2,
      defensiveEfficiency: 98.5,
      pace: 67.5,
      threePointPercentage: 35.1,
      freeThrowPercentage: 72.5,
      reboundRate: 50.8,
      turnoverRate: 17.2,
      experienceRating: 3.2,
    },
  },
  {
    id: "arizona",
    name: "Arizona",
    seed: 4,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Arizona_Wildcats_logo.svg/1200px-Arizona_Wildcats_logo.svg.png",
    colors: {
      primary: "#CC0033",
      secondary: "#003366",
    },
    stats: {
      offensiveEfficiency: 116.8,
      defensiveEfficiency: 93.5,
      pace: 71.2,
      threePointPercentage: 36.8,
      freeThrowPercentage: 74.8,
      reboundRate: 54.2,
      turnoverRate: 15.8,
      experienceRating: 3.9,
    },
  },
  {
    id: "akron",
    name: "Akron",
    seed: 13,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Akron_Zips_logo.svg/1200px-Akron_Zips_logo.svg.png",
    colors: {
      primary: "#041E42",
      secondary: "#A89968",
    },
    stats: {
      offensiveEfficiency: 107.5,
      defensiveEfficiency: 99.2,
      pace: 67.8,
      threePointPercentage: 34.5,
      freeThrowPercentage: 72.2,
      reboundRate: 50.5,
      turnoverRate: 17.5,
      experienceRating: 3.1,
    },
  },
  {
    id: "byu",
    name: "BYU",
    seed: 6,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/BYU_Cougars_logo.svg/1200px-BYU_Cougars_logo.svg.png",
    colors: {
      primary: "#002E5D",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 114.2,
      defensiveEfficiency: 95.5,
      pace: 69.5,
      threePointPercentage: 36.2,
      freeThrowPercentage: 73.8,
      reboundRate: 52.8,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "vcu",
    name: "VCU",
    seed: 11,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/VCU_Rams_logo.svg/1200px-VCU_Rams_logo.svg.png",
    colors: {
      primary: "#000000",
      secondary: "#FFB300",
    },
    stats: {
      offensiveEfficiency: 110.8,
      defensiveEfficiency: 96.8,
      pace: 70.2,
      threePointPercentage: 34.8,
      freeThrowPercentage: 72.5,
      reboundRate: 51.5,
      turnoverRate: 17.2,
      experienceRating: 3.4,
    },
  },
  {
    id: "wisconsin",
    name: "Wisconsin",
    seed: 3,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Wisconsin_Badgers_logo.svg/1200px-Wisconsin_Badgers_logo.svg.png",
    colors: {
      primary: "#C5050C",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 116.5,
      defensiveEfficiency: 93.2,
      pace: 67.8,
      threePointPercentage: 36.5,
      freeThrowPercentage: 74.5,
      reboundRate: 53.5,
      turnoverRate: 15.5,
      experienceRating: 3.9,
    },
  },
  {
    id: "montana",
    name: "Montana",
    seed: 14,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Montana_Grizzlies_logo.svg/1200px-Montana_Grizzlies_logo.svg.png",
    colors: {
      primary: "#999999",
      secondary: "#660033",
    },
    stats: {
      offensiveEfficiency: 106.8,
      defensiveEfficiency: 99.5,
      pace: 68.2,
      threePointPercentage: 34.2,
      freeThrowPercentage: 71.8,
      reboundRate: 50.2,
      turnoverRate: 17.8,
      experienceRating: 3.0,
    },
  },
  {
    id: "saint_marys",
    name: "Saint Mary's",
    seed: 7,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Saint_Mary%27s_Gaels_logo.svg/1200px-Saint_Mary%27s_Gaels_logo.svg.png",
    colors: {
      primary: "#003366",
      secondary: "#CC0000",
    },
    stats: {
      offensiveEfficiency: 113.8,
      defensiveEfficiency: 94.8,
      pace: 68.5,
      threePointPercentage: 36.2,
      freeThrowPercentage: 73.8,
      reboundRate: 52.5,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "vanderbilt",
    name: "Vanderbilt",
    seed: 10,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Vanderbilt_Commodores_logo.svg/1200px-Vanderbilt_Commodores_logo.svg.png",
    colors: {
      primary: "#000000",
      secondary: "#866D4B",
    },
    stats: {
      offensiveEfficiency: 111.2,
      defensiveEfficiency: 96.5,
      pace: 69.2,
      threePointPercentage: 35.5,
      freeThrowPercentage: 73.2,
      reboundRate: 51.8,
      turnoverRate: 16.8,
      experienceRating: 3.4,
    },
  },
  {
    id: "alabama",
    name: "Alabama",
    seed: 2,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Alabama_Crimson_Tide_logo.svg/1200px-Alabama_Crimson_Tide_logo.svg.png",
    colors: {
      primary: "#9E1B32",
      secondary: "#828A8F",
    },
    stats: {
      offensiveEfficiency: 118.2,
      defensiveEfficiency: 92.5,
      pace: 71.5,
      threePointPercentage: 37.2,
      freeThrowPercentage: 74.8,
      reboundRate: 54.2,
      turnoverRate: 15.5,
      experienceRating: 3.9,
    },
  },
  {
    id: "robert_morris",
    name: "Robert Morris",
    seed: 15,
    region: "East",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Robert_Morris_Colonials_logo.svg/1200px-Robert_Morris_Colonials_logo.svg.png",
    colors: {
      primary: "#14234B",
      secondary: "#C60C30",
    },
    stats: {
      offensiveEfficiency: 105.5,
      defensiveEfficiency: 100.2,
      pace: 67.5,
      threePointPercentage: 33.5,
      freeThrowPercentage: 71.5,
      reboundRate: 49.5,
      turnoverRate: 18.5,
      experienceRating: 2.8,
    },
  },
  // West Region
  {
    id: "florida",
    name: "Florida",
    seed: 1,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Florida_Gators_logo.svg/1200px-Florida_Gators_logo.svg.png",
    colors: {
      primary: "#0021A5",
      secondary: "#FA4616",
    },
    stats: {
      offensiveEfficiency: 113.5,
      defensiveEfficiency: 95.2,
      pace: 70.2,
      threePointPercentage: 35.8,
      freeThrowPercentage: 73.8,
      reboundRate: 52.5,
      turnoverRate: 16.2,
      experienceRating: 3.6,
    },
  },
  {
    id: "norfolk_st",
    name: "Norfolk St.",
    seed: 16,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Norfolk_State_Spartans_logo.svg/1200px-Norfolk_State_Spartans_logo.svg.png",
    colors: {
      primary: "#003A63",
      secondary: "#E51937",
    },
    stats: {
      offensiveEfficiency: 100.2,
      defensiveEfficiency: 101.5,
      pace: 68.0,
      threePointPercentage: 33.2,
      freeThrowPercentage: 70.2,
      reboundRate: 48.8,
      turnoverRate: 18.5,
      experienceRating: 2.8,
    },
  },
  {
    id: "uconn",
    name: "UConn",
    seed: 8,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Connecticut_Huskies_logo.svg/1200px-Connecticut_Huskies_logo.svg.png",
    colors: {
      primary: "#000E2F",
      secondary: "#E4002B",
    },
    stats: {
      offensiveEfficiency: 120.5,
      defensiveEfficiency: 90.2,
      pace: 69.5,
      threePointPercentage: 37.8,
      freeThrowPercentage: 75.8,
      reboundRate: 55.5,
      turnoverRate: 14.5,
      experienceRating: 4.2,
    },
  },
  {
    id: "oklahoma",
    name: "Oklahoma",
    seed: 9,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Oklahoma_Sooners_logo.svg/1200px-Oklahoma_Sooners_logo.svg.png",
    colors: {
      primary: "#841617",
      secondary: "#FDF9D8",
    },
    stats: {
      offensiveEfficiency: 113.5,
      defensiveEfficiency: 94.8,
      pace: 68.8,
      threePointPercentage: 36.2,
      freeThrowPercentage: 74.1,
      reboundRate: 52.5,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "memphis",
    name: "Memphis",
    seed: 5,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Memphis_Tigers_logo.svg/1200px-Memphis_Tigers_logo.svg.png",
    colors: {
      primary: "#003087",
      secondary: "#898D8D",
    },
    stats: {
      offensiveEfficiency: 115.5,
      defensiveEfficiency: 95.2,
      pace: 70.5,
      threePointPercentage: 36.5,
      freeThrowPercentage: 74.2,
      reboundRate: 53.1,
      turnoverRate: 16.1,
      experienceRating: 3.8,
    },
  },
  {
    id: "colorado_st",
    name: "Colorado St.",
    seed: 12,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Colorado_State_Rams_logo.svg/1200px-Colorado_State_Rams_logo.svg.png",
    colors: {
      primary: "#1E4D2B",
      secondary: "#C8C372",
    },
    stats: {
      offensiveEfficiency: 115.8,
      defensiveEfficiency: 94.2,
      pace: 68.8,
      threePointPercentage: 36.2,
      freeThrowPercentage: 74.0,
      reboundRate: 53.5,
      turnoverRate: 15.8,
      experienceRating: 3.8,
    },
  },
  {
    id: "maryland",
    name: "Maryland",
    seed: 4,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Maryland_Terrapins_logo.svg/1200px-Maryland_Terrapins_logo.svg.png",
    colors: {
      primary: "#E03A3E",
      secondary: "#FFD520",
    },
    stats: {
      offensiveEfficiency: 116.8,
      defensiveEfficiency: 93.5,
      pace: 70.8,
      threePointPercentage: 36.5,
      freeThrowPercentage: 74.2,
      reboundRate: 53.8,
      turnoverRate: 15.5,
      experienceRating: 3.8,
    },
  },
  {
    id: "grand_canyon",
    name: "Grand Canyon",
    seed: 13,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Grand_Canyon_Antelopes_logo.svg/1200px-Grand_Canyon_Antelopes_logo.svg.png",
    colors: {
      primary: "#522D80",
      secondary: "#F66733",
    },
    stats: {
      offensiveEfficiency: 107.5,
      defensiveEfficiency: 99.2,
      pace: 67.5,
      threePointPercentage: 34.2,
      freeThrowPercentage: 72.2,
      reboundRate: 50.2,
      turnoverRate: 17.8,
      experienceRating: 3.0,
    },
  },
  {
    id: "missouri",
    name: "Missouri",
    seed: 6,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Missouri_Tigers_logo.svg/1200px-Missouri_Tigers_logo.svg.png",
    colors: {
      primary: "#F1B82D",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 114.5,
      defensiveEfficiency: 95.2,
      pace: 70.8,
      threePointPercentage: 36.0,
      freeThrowPercentage: 73.5,
      reboundRate: 52.8,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "drake",
    name: "Drake",
    seed: 11,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Drake_Bulldogs_logo.svg/1200px-Drake_Bulldogs_logo.svg.png",
    colors: {
      primary: "#004477",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 111.5,
      defensiveEfficiency: 96.2,
      pace: 68.5,
      threePointPercentage: 35.2,
      freeThrowPercentage: 73.0,
      reboundRate: 51.8,
      turnoverRate: 16.5,
      experienceRating: 3.4,
    },
  },
  {
    id: "texas_tech",
    name: "Texas Tech",
    seed: 3,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Texas_Tech_Red_Raiders_logo.svg/1200px-Texas_Tech_Red_Raiders_logo.svg.png",
    colors: {
      primary: "#CC0000",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 112.8,
      defensiveEfficiency: 95.5,
      pace: 69.5,
      threePointPercentage: 35.5,
      freeThrowPercentage: 73.5,
      reboundRate: 52.2,
      turnoverRate: 16.5,
      experienceRating: 3.5,
    },
  },
  {
    id: "unc_wilmington",
    name: "UNC Wilmington",
    seed: 14,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/UNC_Wilmington_Seahawks_logo.svg/1200px-UNC_Wilmington_Seahawks_logo.svg.png",
    colors: {
      primary: "#006F71",
      secondary: "#FFB81C",
    },
    stats: {
      offensiveEfficiency: 106.5,
      defensiveEfficiency: 99.8,
      pace: 68.0,
      threePointPercentage: 34.0,
      freeThrowPercentage: 71.5,
      reboundRate: 50.0,
      turnoverRate: 18.0,
      experienceRating: 2.9,
    },
  },
  {
    id: "kansas",
    name: "Kansas",
    seed: 7,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Kansas_Jayhawks_logo.svg/1200px-Kansas_Jayhawks_logo.svg.png",
    colors: {
      primary: "#0051BA",
      secondary: "#E8000D",
    },
    stats: {
      offensiveEfficiency: 117.2,
      defensiveEfficiency: 93.8,
      pace: 70.5,
      threePointPercentage: 36.5,
      freeThrowPercentage: 74.8,
      reboundRate: 54.0,
      turnoverRate: 15.5,
      experienceRating: 3.9,
    },
  },
  {
    id: "arkansas",
    name: "Arkansas",
    seed: 10,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Arkansas_Razorbacks_logo.svg/1200px-Arkansas_Razorbacks_logo.svg.png",
    colors: {
      primary: "#9D2235",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 111.2,
      defensiveEfficiency: 96.5,
      pace: 70.5,
      threePointPercentage: 35.2,
      freeThrowPercentage: 72.8,
      reboundRate: 51.5,
      turnoverRate: 16.8,
      experienceRating: 3.4,
    },
  },
  {
    id: "st_johns",
    name: "St. John's",
    seed: 2,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/St._John%27s_Red_Storm_logo.svg/1200px-St._John%27s_Red_Storm_logo.svg.png",
    colors: {
      primary: "#BA0C2F",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 114.2,
      defensiveEfficiency: 95.5,
      pace: 69.5,
      threePointPercentage: 36.2,
      freeThrowPercentage: 73.8,
      reboundRate: 52.8,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "omaha",
    name: "Omaha",
    seed: 15,
    region: "West",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Omaha_Mavericks_logo.svg/1200px-Omaha_Mavericks_logo.svg.png",
    colors: {
      primary: "#000000",
      secondary: "#D71920",
    },
    stats: {
      offensiveEfficiency: 105.8,
      defensiveEfficiency: 100.2,
      pace: 68.0,
      threePointPercentage: 33.8,
      freeThrowPercentage: 71.5,
      reboundRate: 49.8,
      turnoverRate: 18.2,
      experienceRating: 2.8,
    },
  },
  // Midwest Region
  {
    id: "houston",
    name: "Houston",
    seed: 1,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Houston_Cougars_logo.svg/1200px-Houston_Cougars_logo.svg.png",
    colors: {
      primary: "#C8102E",
      secondary: "#231F20",
    },
    stats: {
      offensiveEfficiency: 120.2,
      defensiveEfficiency: 90.5,
      pace: 68.8,
      threePointPercentage: 37.5,
      freeThrowPercentage: 75.5,
      reboundRate: 55.2,
      turnoverRate: 14.8,
      experienceRating: 4.1,
    },
  },
  {
    id: "siu_edwardsville",
    name: "SIU Edwardsville",
    seed: 16,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/SIU_Edwardsville_Cougars_logo.svg/1200px-SIU_Edwardsville_Cougars_logo.svg.png",
    colors: {
      primary: "#CC0000",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 100.2,
      defensiveEfficiency: 101.5,
      pace: 68.0,
      threePointPercentage: 33.2,
      freeThrowPercentage: 70.2,
      reboundRate: 48.8,
      turnoverRate: 18.5,
      experienceRating: 2.8,
    },
  },
  {
    id: "gonzaga",
    name: "Gonzaga",
    seed: 8,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Gonzaga_Bulldogs_logo.svg/1200px-Gonzaga_Bulldogs_logo.svg.png",
    colors: {
      primary: "#041E42",
      secondary: "#C8102E",
    },
    stats: {
      offensiveEfficiency: 116.2,
      defensiveEfficiency: 94.5,
      pace: 71.2,
      threePointPercentage: 36.8,
      freeThrowPercentage: 74.5,
      reboundRate: 53.8,
      turnoverRate: 15.8,
      experienceRating: 3.8,
    },
  },
  {
    id: "georgia",
    name: "Georgia",
    seed: 9,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Georgia_Bulldogs_logo.svg/1200px-Georgia_Bulldogs_logo.svg.png",
    colors: {
      primary: "#BA0C2F",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 113.5,
      defensiveEfficiency: 94.8,
      pace: 68.8,
      threePointPercentage: 36.2,
      freeThrowPercentage: 74.1,
      reboundRate: 52.5,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "clemson",
    name: "Clemson",
    seed: 5,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Clemson_Tigers_logo.svg/1200px-Clemson_Tigers_logo.svg.png",
    colors: {
      primary: "#F66733",
      secondary: "#522D80",
    },
    stats: {
      offensiveEfficiency: 114.5,
      defensiveEfficiency: 95.2,
      pace: 69.2,
      threePointPercentage: 36.0,
      freeThrowPercentage: 73.5,
      reboundRate: 52.8,
      turnoverRate: 16.2,
      experienceRating: 3.7,
    },
  },
  {
    id: "mcneese",
    name: "McNeese",
    seed: 12,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/McNeese_Cowboys_logo.svg/1200px-McNeese_Cowboys_logo.svg.png",
    colors: {
      primary: "#00529B",
      secondary: "#FFB81C",
    },
    stats: {
      offensiveEfficiency: 107.5,
      defensiveEfficiency: 99.2,
      pace: 67.5,
      threePointPercentage: 34.2,
      freeThrowPercentage: 72.2,
      reboundRate: 50.5,
      turnoverRate: 17.5,
      experienceRating: 3.0,
    },
  },
  {
    id: "purdue",
    name: "Purdue",
    seed: 4,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Purdue_Boilermakers_logo.svg/1200px-Purdue_Boilermakers_logo.svg.png",
    colors: {
      primary: "#CEB888",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 118.8,
      defensiveEfficiency: 92.2,
      pace: 68.5,
      threePointPercentage: 37.5,
      freeThrowPercentage: 75.0,
      reboundRate: 54.5,
      turnoverRate: 15.2,
      experienceRating: 4.0,
    },
  },
  {
    id: "high_point",
    name: "High Point",
    seed: 13,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/High_Point_Panthers_logo.svg/1200px-High_Point_Panthers_logo.svg.png",
    colors: {
      primary: "#4F286F",
      secondary: "#A8996E",
    },
    stats: {
      offensiveEfficiency: 106.8,
      defensiveEfficiency: 99.5,
      pace: 67.8,
      threePointPercentage: 34.5,
      freeThrowPercentage: 71.8,
      reboundRate: 50.2,
      turnoverRate: 17.8,
      experienceRating: 3.0,
    },
  },
  {
    id: "illinois",
    name: "Illinois",
    seed: 6,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Illinois_Fighting_Illini_logo.svg/1200px-Illinois_Fighting_Illini_logo.svg.png",
    colors: {
      primary: "#E84A27",
      secondary: "#13294B",
    },
    stats: {
      offensiveEfficiency: 117.2,
      defensiveEfficiency: 93.5,
      pace: 70.5,
      threePointPercentage: 36.8,
      freeThrowPercentage: 74.5,
      reboundRate: 53.8,
      turnoverRate: 15.5,
      experienceRating: 3.8,
    },
  },
  {
    id: "texas_xavier",
    name: "Texas/Xavier",
    seed: 11,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Texas_Longhorns_logo.svg/1200px-Texas_Longhorns_logo.svg.png",
    colors: {
      primary: "#BF5700",
      secondary: "#333F48",
    },
    stats: {
      offensiveEfficiency: 110.8,
      defensiveEfficiency: 96.8,
      pace: 70.2,
      threePointPercentage: 34.8,
      freeThrowPercentage: 72.5,
      reboundRate: 51.5,
      turnoverRate: 17.2,
      experienceRating: 3.4,
    },
  },
  {
    id: "kentucky",
    name: "Kentucky",
    seed: 3,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Kentucky_Wildcats_logo.svg/1200px-Kentucky_Wildcats_logo.svg.png",
    colors: {
      primary: "#0033A0",
      secondary: "#FFFFFF",
    },
    stats: {
      offensiveEfficiency: 117.5,
      defensiveEfficiency: 93.2,
      pace: 71.0,
      threePointPercentage: 37.0,
      freeThrowPercentage: 74.5,
      reboundRate: 54.0,
      turnoverRate: 15.2,
      experienceRating: 3.8,
    },
  },
  {
    id: "troy",
    name: "Troy",
    seed: 14,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Troy_Trojans_logo.svg/1200px-Troy_Trojans_logo.svg.png",
    colors: {
      primary: "#8C2132",
      secondary: "#A3AAAE",
    },
    stats: {
      offensiveEfficiency: 106.5,
      defensiveEfficiency: 99.8,
      pace: 68.0,
      threePointPercentage: 34.0,
      freeThrowPercentage: 71.5,
      reboundRate: 50.0,
      turnoverRate: 18.0,
      experienceRating: 2.9,
    },
  },
  {
    id: "ucla",
    name: "UCLA",
    seed: 7,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/UCLA_Bruins_logo.svg/1200px-UCLA_Bruins_logo.svg.png",
    colors: {
      primary: "#2D68C4",
      secondary: "#F2A900",
    },
    stats: {
      offensiveEfficiency: 113.8,
      defensiveEfficiency: 96.8,
      pace: 70.2,
      threePointPercentage: 34.8,
      freeThrowPercentage: 72.5,
      reboundRate: 51.5,
      turnoverRate: 17.2,
      experienceRating: 3.4,
    },
  },
  {
    id: "utah_st",
    name: "Utah St.",
    seed: 10,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Utah_State_Aggies_logo.svg/1200px-Utah_State_Aggies_logo.svg.png",
    colors: {
      primary: "#00263A",
      secondary: "#8B8D8F",
    },
    stats: {
      offensiveEfficiency: 105.8,
      defensiveEfficiency: 100.2,
      pace: 68.0,
      threePointPercentage: 33.8,
      freeThrowPercentage: 71.5,
      reboundRate: 49.8,
      turnoverRate: 18.2,
      experienceRating: 2.8,
    },
  },
  {
    id: "tennessee",
    name: "Tennessee",
    seed: 2,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Tennessee_Volunteers_logo.svg/1200px-Tennessee_Volunteers_logo.svg.png",
    colors: {
      primary: "#FF8200",
      secondary: "#58595B",
    },
    stats: {
      offensiveEfficiency: 118.2,
      defensiveEfficiency: 92.5,
      pace: 71.5,
      threePointPercentage: 37.2,
      freeThrowPercentage: 74.8,
      reboundRate: 54.2,
      turnoverRate: 15.5,
      experienceRating: 3.9,
    },
  },
  {
    id: "wofford",
    name: "Wofford",
    seed: 15,
    region: "Midwest",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Wofford_Terriers_logo.svg/1200px-Wofford_Terriers_logo.svg.png",
    colors: {
      primary: "#846F51",
      secondary: "#000000",
    },
    stats: {
      offensiveEfficiency: 105.5,
      defensiveEfficiency: 100.5,
      pace: 67.8,
      threePointPercentage: 33.5,
      freeThrowPercentage: 71.2,
      reboundRate: 49.8,
      turnoverRate: 18.2,
      experienceRating: 2.8,
    },
  },
];

// Function to get team by ID
export const getTeamById = (id: string): Team | undefined => {
  return teams.find(team => team.id === id);
};

// Function to get teams by region
export const getTeamsByRegion = (region: string): Team[] => {
  return teams.filter(team => team.region === region);
}; 